services:
  tubesage:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - ollama
    networks:
      - ollama-docker

  ollama:
    build:
      context: .
      dockerfile: DockerfileOllama
    ports:
      - "11434:11434"
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - ollama-docker

networks:
  ollama-docker:
